### PR TITLE
Replaced regexp `match` with faster `test`

### PR DESCRIPTION
**Pull request by TrySound**
Creating array is much more heavy operation than any boolean operation.

### CODE REVIEW

**Comment by peduarte** [comment]
Aceita ai orgulhoso.

**Comment by TrySound** [comment]
@peduarte English please. You are not the only one here.

**Comment by henriquea** [comment]
@TrySound Cool. @peduarte is a good friend, he's just jealous because of minigrid's success 😂

**Comment by TrySound** [comment]
Okay :)

**Comment by peduarte** [comment]
😂😐




👋


(does emoji count as a language?)

**Pull request merged**
