### PR TITLE
Added containerLoaded and itemLoaded options

### PR DESCRIPTION
**Pull request by TrySound**
I'd like to control which class name adds to my elements.

### CODE REVIEW

**Comment by TrySound** [comment]
It's minor (compatible feature) change

**Comment by henriquea** [comment]
@TrySound IMO this is very personal. My goal with this library is to *drop off* something that works over configuration. I already changed the gutter to zero now you have to pass three properties instead of two. Maybe `loaded` isn't the right class name and `ready` would be more appropriated.

**Comment by TrySound** [comment]
@henriquea It still appends automatically. But there is an able to pass custom classes. We don't have guarantee that first class won't be some util class. It's not personal, it's flexible.

**Comment by henriquea** [comment]
@TrySound that's true! Merging this in a bit. Thanks again mate!

**Pull request merged**
