### PR TITLE
Let props.item (itemsNodeList) be either an existing NodeList or …

### PR DESCRIPTION
**Pull request by soenkekluth**
…a selector string

### CODE REVIEW

**Comment by henriquea** [comment]
thanks @soenkekluth 👍

**Comment by soenkekluth** [comment]
just thought - to be more flexible we should also check for 
`props.item instanceof HTMLCollection`
in case you just simply use `grid.children`

I will PR again. 
what do you think - also check for an instance of an Array to be even more flexible in collecting the item nodes outside minigrid?

**Comment by henriquea** [comment]
@soenkekluth hmm I'm thinking that most of the cases this wouldn't happen. I don't want to bloat the API. Check against `HTMLCollection` would make sense however `instance of Array` sounds like an exceptional case no?

**Comment by henriquea** [comment]
@soenkekluth by the way please use the branch `next` for PR. I'll update the CONTRIBUTING doc.

**Comment by henriquea** [comment]
@soenkekluth please ignore the branch next request. I just deleted this branch. Cheers

**Pull request merged**
