### PR TITLE
Update index.js

### PR DESCRIPTION
**Pull request by pulse-studio**

### CODE REVIEW

**Comment by pulse-studio** [comment]
minigrid not working.

**Comment by henriquea** [comment]
@pulse-studio hey folks! The PR looks alright but there was a reason to set `display: inline` which I can't remember now 😄 I'll have a look at it again and come back to you 👍

**Comment by pulse-studio** [comment]
Good!
Waiting for news;) :+1:

**Comment by henriquea** [comment]
hi @pulse-studio it is working already. The issue on that jsbin is because you can't import scripts from GitHub directly so this `src="https://github.com/henriquea/minigrid/blob/master/src/index.js"` won't work. I replaced the `src` using npmcdn and you can see the result [here](http://jsbin.com/gaduxonogu/edit?html,js,output).

**Comment by pulse-studio** [comment]
On the local project I have does not work.

**Comment by pulse-studio** [comment]
Not working!
last version 3.0.4.
demo - http://pulse.studio/minigrid/

Version 3.0.3 works

**Pull request closed without merging**
